### ISSUE TITLE
Loading Location Issue !!!

### ISSUE THREAD

**Issue by sarojghalan** [anjitpariyar/Awakened_Anjit_with_Google_map#1]
![image](https://github.com/anjitpariyar/Awakened_Anjit_with_Google_map/assets/88360959/7a1a5508-84aa-44d8-83f6-a78a8a7cc59b)

**Comment by anjitpariyar** [comment]
@sarojghalan it asks for the location permission and you need to provide it,
Additionally, you need to add env variables as well.
I do notice a bit conditional issue, which I have fixed, 
would you kindly check again 
it should look like this 
![image](https://github.com/anjitpariyar/Awakened_Anjit_with_Google_map/assets/45827003/7570f8d2-9e84-452d-bfac-578bf736edb1)

**Comment by sarojghalan** [comment]
Could you please advise what I should write inside`.env` file, as my location has already been `enabled`.

**Comment by anjitpariyar** [comment]
> ``.

this
NEXT_PUBLIC_BACKEND_API=https://lz4.overpass-api.de/api

**Comment by sarojghalan** [comment]
Yes it is failing to fetch : 

![image](https://github.com/anjitpariyar/Awakened_Anjit_with_Google_map/assets/88360959/5ebedc57-66b2-431a-9039-dcfaf07e106c)

**Comment by anjitpariyar** [comment]
@sarojghalan Sorry looks like an extra character was added on env. and I appended the rest API URLs in the code so then only you can get the full API URL . check on the network tab like this
![image](https://github.com/anjitpariyar/Awakened_Anjit_with_Google_map/assets/45827003/c0276615-f43b-40b2-9aa7-908aba6b7dbb)

I pushed env on the gitas well, you can take a pull from the main again and try to run again.

**Comment by anjitpariyar** [comment]
I guess the issue has been successfully addressed and resolved. Thank you for bringing this up
